version: "3"
services:
  githubapi:
    image: ${ID}/githubserviceapi:1.0
    restart: always
    container_name: githubserviceapi
    depends_on:
      - apigateway
    
  identityapi:
    image: ${ID}/identityserviceapi:1.0
    restart: always
    container_name: identityserviceapi
    depends_on:
      - identityservicestore

  mailapi:
    image: ${ID}/mailserviceapi:1.0
    restart: always
    container_name: mailserviceapi
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8083"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - C:\Users\Intel\.aspnet\https:/root/.aspnet/https/
    ports:
      - "8082:80"
      - "8083:443"
    
  
  
  apigateway:
    image: ${ID}/apigateway:1.0
    container_name: api
    restart: always
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - C:\Users\Intel\.aspnet\https:/root/.aspnet/https/
    ports:
      - "8080:80"
      - "8081:443"


  identityservicestore:
    image: postgres
    restart: always
    container_name: identity_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_vol:/var/lib/postgresql/data
  
  githubservicestore:
    image: postgres
    restart: always
    container_name: github_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_vol2:/var/lib/postgresql/data
volumes:
  db_vol:
  db_vol2: